### PR TITLE
Jw/upgrade monaco

### PR DESCRIPTION
**Pull request by jaredwy**

### CODE REVIEW

**Comment by RabsRincon** [comment]
I can't compile anything on this branch. Every compilation seems to hang forever (No asm output + footter stays at "- Compiling...")

**Comment by jaredw** [comment]
Ah. I thought that was just me on OS X. I haven’t changed anything on the server so I’ll try a rebase from master. Perhaps I branched off a bad commit.

**Comment by RabsRincon** [comment]
@jaredw Are you going to use this branch to upgrade to 0.12?

**Comment by jaredwy** [comment]
Yeah :) in about an hour!

**Comment by mattgodbolt** [comment]
@jaredw in the light of your shiny new PR, I'm going to close this. If only to appease the slight scared feeling I get seeing so many outstanding PRs to work with :)

**Comment by jaredwy** [comment]
Oh didn't know this was still open! No issues there.

**Pull request closed without merging**
