### PR TITLE
Add LDC latest CI

### PR DESCRIPTION
**Pull request by JohanEngelen**
Depends on https://github.com/mattgodbolt/compiler-explorer-image/pull/150

### CODE REVIEW

**Comment by JohanEngelen** [comment]
I notice that dmd2-nightly is not listed on d.godbolt.org, although we have it here: https://github.com/mattgodbolt/compiler-explorer/blob/master/etc/config/d.amazon.properties#L74-L75

Something wrong with the installation of it?

**Comment by RabsRincon** [comment]
Yes! I just filled #1219

**Comment by JohanEngelen** [comment]
@RabsRincon Fixed the merge conflict, it should work now!

**Comment by RabsRincon** [comment]
Thanks again for the addition! :)

**Pull request merged**
