### PR TITLE
[WIP] Compiler Explorer on Azure

### PR DESCRIPTION
**Pull request by partouf**
Wanted to share my progress so far.

Note: I had to use batchfiles, because the .options don't allow spaces in paths. Maybe we should look into that instead of with using cmd /C as a compile-wrapper?

Todo:

- [x] Add libraries
- [x] Make a run script
- [ ] Test libraries
- [x] Make something that allows CE to run on bootup without having to log in
- [x] Unmix the commits that don't belong here

### CODE REVIEW

**Comment by AraHaan** [comment]
it is possible to override spaces in paths by encasing the environment variable to get the current working directory inside of double quotes making it an string.

**Comment by partouf** [comment]
I'm not entirely sure what you mean, but the .options properties seem to completely ignore quotes.
And the current working directory would be either C:\CE\ or C:\tmp\sometempfolder\ depending on if you're in node code or execution. So I don't think that would be useful.

**Comment by AraHaan** [comment]
I dont like hard coding in C:\ because what if their linux is on C:\ and windows is on E:\?

I would better use ``%SystemDrive%`` environment Variable value instead hard coded into windows.

**Comment by partouf** [comment]
Ah now I understand the confusion. I understand there would be a problem when you have things installed on other drives or folders.

These paths are based on a Default virtual machine with Visual Studio preinstalled provided by Microsoft on Azure. We'll need a lot of different changes and settings to make it work out of the box on any other Windows environment.

But I'll keep it in mind.

**Comment by AndrewPardoe** [comment]
@partouf if I can help with this, let me know.

**Pull request closed without merging**
