### PR TITLE
Add Brigand metaprogramming library

### PR DESCRIPTION
**Pull request by nilsdeppe**
I'm putting in a PR to the sister repo as well: https://github.com/mattgodbolt/compiler-explorer-image/pull/64

### CODE REVIEW

**Comment by RabsRincon** [comment]
Hi! First of all, thank you so much for taking the time to improve Compiler Explorer, we really appreciate it :)

Both PRs look, good, but one thing needs to change. We try to stick as much as possible to "URLs live forever". So, instead of pointing to trunk, point to the latest release (In this case https://github.com/edouarda/brigand/releases/tag/1.3.0) so the output will always be the same. We can afford to later add more versions of the lib. I will also give you some comments on the sister repo PR for the installation process.

Again, thanks for your contribuition!

**Comment by nilsdeppe** [comment]
Okay, that sounds good! Is it okay to have "trunk" in addition to versions? There are some bug fixes and features that haven't yet made it into a release that I and probably others would want to use.

**Comment by RabsRincon** [comment]
Yes! I was going to suggest adding trunk as an addiotional version! Good catch :D

**Comment by mattgodbolt** [comment]
Hi @nilsdeppe - were you able to add both trunk and versioned versions OK?

**Comment by nilsdeppe** [comment]
@mattgodbolt thanks for asking! Sorry, it's been a busy week, I just pushed the updates now. Please let me know if things are correct now.

**Comment by RabsRincon** [comment]
Don't worry! This is great, merging now. It should hit the live site some time this week.

**Comment by nilsdeppe** [comment]
Awesome, thank you very much!

**Comment by RabsRincon** [comment]
Hi @nilsdeppe. I just want to let you know that Brigand should now be available on CE for everyone :+1: (It might take some minutes for it to appear) Thank you so much for it!

**Comment by nilsdeppe** [comment]
@RabsRincon @mattgodbolt awesome, thank you so much for the awesome tool!

**Pull request merged**
