### PR TITLE
OCaml language support

### PR DESCRIPTION
**Pull request by Freyr666**
A very basic OCaml support. Editor mode may (and shall) be improved, a demangler will be added later.

### CODE REVIEW

**Comment by RabsRincon** [comment]
Hi! Sorry we took so long to answer back, most of us have been busy with holidays. This side of the changes look great (Minus the missing features, but we can, as you said, add them at a later date). The only stopping issue is the installation of the ocamel compilers themselves, but we can track that in the sister repo PR. I'll merge this one as soon as the compilers are properly installed :)

**Comment by ubsan** [comment]
oh this is awesome

**Comment by mattgodbolt** [comment]
Compilers now installed on the host, and build steps etc canonified with Docker.

**Comment by mattgodbolt** [comment]
It's now live on https://godbolt.org/beta -- but there's an issue. Wherever the compiler is writing to is not read/write:

```
usr/bin/ld: cannot open output file a.out: Read-only file system
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking
Compiler returned: 2
```

Not knowing anything about ocaml compilation, @Freyr666 do you have any insight into what the compiler might be doing? If it's trying to write into the current directory, that would explain things (for obvious reasons we mount the Compiler Explorer code read-only. I unfortunately don't have time right now to dig further.

**Comment by Freyr666** [comment]
Ok, it works with the `-c` flag, it seems the linking stage is unnecessary, am I right? It shouldn't produce any binary?

**Comment by Freyr666** [comment]
I think #1259 should fix it.

**Comment by mattgodbolt** [comment]
(Indeed it did. Discussion moved there :))

**Comment by RabsRincon** [comment]
Hi @Freyr666! Thanks again for taking the time to implement OCaml support. I'm in the process of pushing a new update to the live site. Do you have any twitter handle we can use to thank you once it goes live? We can use the GitHub one if not, too :)

**Pull request merged**
