### PR TITLE
First attempt at storing all queries on S3 (and deleting after)

### PR DESCRIPTION
**Pull request by mattgodbolt**
In the hope of tracking down some of our bugs. Later on we might want to log longer running queries; we may need to update the privacy policy for the latter.

Should help us with #1336 

Draft until I get a bit of feedback; and also have a chance to test in staging or beta.

### CODE REVIEW

**Comment by apmorton** [comment]
Haven't looked over everything in detail or tried the code yet, but at a cursory glance I don't know if this will work as is to log the "query of death" we are seeing.

The important thing to note is that _those queries don't actually throw any exceptions or themselves fail_, they just take forever and block up the node event loop in the process. So if I had to guess, they will pass through this code with `erase = true`

**Comment by mattgodbolt** [comment]
@apmorton my instinct is that they block the event loop forever, which means they _don't_  pass erase=true, as the callback never comes. Thus the process is eventually killed and then the results are left on s3. Unless I've missed something :)

**Comment by mattgodbolt** [comment]
(the intent of the "erase" is to catch things where we ICE, which is a separate set of (potential) bugs)

**Comment by mattgodbolt** [comment]
Gonna close this after @apmorton 's much more cunning idea worked out :)

**Pull request closed without merging**
