### PR TITLE
Binary support for MSVC

### PR DESCRIPTION
**Pull request by partouf**
Support for Binary mode for MSVC via objdump.

Requirements for binary mode are that the LIB environment variable contains the paths to at least (replace various version numbers):
* C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/**lib**/x64
* C:/Program Files (x86)/Windows Kits/10/Lib/10.0.17134.0/**um**/x64
* C:/Program Files (x86)/Windows Kits/10/Lib/10.0.17134.0/**ucrt**/x64

But since it requires the Windows SDK kit, it's not possible (afaik) to run it on the Amazon servers, so I disabled that for now.

So this PR is more of a heads up for @ubsan 

On Windows I have tested this with the objdump.exe from this mingw binary package: https://sourceforge.net/projects/mingw-w64/

Note that it isn't possible to show line colouring, as the VS map file does not export that information.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
How does this interact with the www.godbolt.ms stuff? Presumably it's a win for that too? :)

**Comment by partouf** [comment]
> How does this interact with the [www.godbolt.ms](http://www.godbolt.ms) stuff? Presumably it's a win for that too? :)

It would enable them to enable binary mode, but the prerequisite is that they have to install mingw objdump and configure it in their properties file.

**Comment by mattgodbolt** [comment]
@Rastaban any thoughts on this? Would be cool to support binary mode too.

**Comment by partouf** [comment]
Going to rebase and retest this code and merge it in a way so it doesn't affect anything. But I need the improvements for execution support and map support for other languages.

**Comment by partouf** [comment]
This should be it, it works and is disabled unless configured

**Pull request merged**
