### PR TITLE
Add godbolt.ms as a remote compiler explorer!

### PR DESCRIPTION
**Pull request by ubsan**
Whee!

### CODE REVIEW

**Comment by RabsRincon** [comment]
As discussed on Slack (So it does not go forggoten):

 It's worth switching every compiler we have running on wine to MS. To keep old links working, the ids on MS's side have to either be the same, or be added as aliases.

Ideally we would end up getting the new compilers + a 1 for ~1 instance of the versions we do currently support.

**Comment by ubsan** [comment]
@partouf yeah, and the people at Microsoft who are working on this now would have to add MSVC 15.0 and 15.4, if they wanted to replace the two VS2017 compilers. How would they alias the old names to the new names, tho?

**Comment by RabsRincon** [comment]
@ubsan Compilers have an `alias` property (for example: https://github.com/mattgodbolt/compiler-explorer/blob/master/etc/config/c%2B%2B.amazon.properties#L374) that can be set, and any compiler referring to the alias will find it.

**Comment by Rastaban** [comment]
We are working on getting https up on the Microsoft hosted site, I will let you know when there is an update.  It would be helpful if we could talk to someone about how it is handled on your site because this is all new to us compiler devs.  Would @mattgodbolt be the best one to talk about that?

Also yes to your privacy policy.  It would probably be good to add a link to http://privacy.microsoft.com and explain what it is doing.  Would you like us (Microsoft) to update that, or can it be added to this PR?

**Comment by partouf** [comment]
> We are working on getting https up on the Microsoft hosted site, I will let you know when there is an update. It would be helpful if we could talk to someone about how it is handled on your site because this is all new to us compiler devs. Would @mattgodbolt be the best one to talk about that?

As far as I know, the node webserver is not set up to handle https (the library we use can do it, but we don't use it). I think Matt has setup an Amazon/Cloudfront proxy thing to handle https requests and forward them to the node webserver.

I'm not sure what you use, but within Azure there are options to do the same https://docs.microsoft.com/en-us/azure/application-gateway/create-ssl-portal (I've never tried this)

> 
> Also yes to your privacy policy. It would probably be good to add a link to http://privacy.microsoft.com and explain what it is doing. Would you like us (Microsoft) to update that, or can it be added to this PR?

**Comment by mattgodbolt** [comment]
> Also yes to your privacy policy. It would probably be good to add a link to http://privacy.microsoft.com and explain what it is doing. Would you like us (Microsoft) to update that, or can it be added to this PR?

We can add it to this PR too. Be aware changing the PP will cause popups to re-confirm it when we merge. See also #1109 to maybe consider mitigating this.

Thanks again for your help on this :)

**Comment by mattgodbolt** [comment]
Hi!

Seems like https is now available on the MS link! Yay!

I'll hold off merging this until I get the OK from MS: both on the wording for the PP change and the "ok" to actually link the sites!

I guess I'll need to know who my point of contact is if I need to change anything on the MS side of things too.

Thanks! Exciting times!

**Comment by partouf** [comment]
After this is merged, I'd like to have the properties file from the MS instance in the rep, or a separate fork if needed. Would make it easier to communicate the compiler aliasing, changes to CE that affect the MS side and future binary support.

**Comment by Rastaban** [comment]
You can use me as the contact at Microsoft (philc@microsoft.com), you also have Dale's contact information from our SSL email chain.

You have the OK on our side to link the sites.  I will need to get back to you on the privacy policy though.

**Comment by mattgodbolt** [comment]
Thanks: have emailed you both. Hope to get this merged soon (esp once #1125 is merged too)

**Comment by mattgodbolt** [comment]
I have updated the PP with the wording we discussed over email, and if you wish to have it changed of course we will. I'm going to merge this but will continue to discuss the other issues, namely:

* knowing which version of CE is on www.godbolt.ms
* knowing the properties file (per @partouf's comment)
* also we'll need to think at some point in the future about how the libraries one can pick could work.

Thanks again for your work on this! I'm super excited and hope to roll this out this evening!

**Pull request merged**
