### PR TITLE
Point python compilers to opt installed source. Enable non-3.6 versions

### LINKED ISSUE #1748: Install more Python versions
As of now, only Python 3.6 is available on the site. We should add more versions, and install them under the usual `/opt/compiler-explorer/` dir, instead of relying on they existing on other routes as Python 3.6 currently does.

c.f: #1658

### PR DESCRIPTION
**Pull request by CraftSpider**
Closes #1748
Relies on https://github.com/mattgodbolt/compiler-explorer-image/pull/313 for the compilers existing in the labelled locations

### CODE REVIEW

**Comment by partouf** [comment]
Hi, thanks for the PR!
Changes to python.amazon.properties make sense, but those paths should not be in defaults.properties

**Comment by mattgodbolt** [comment]
Thanks so much for taking the time to do this. As @partouf says can you just update the `amazon` properties: regular users running the site locally will want the defaults pointing at "sensible" places like `/usr/bin/python3.6` or similar.

Thanks in advance, Matt

**Comment by CraftSpider** [comment]
Alright, thanks for the review, I'll fix the paths

**Comment by apmorton** [comment]
Small correction, you should simply leave the default properties how they were. If no absolute path is specified CE will resolve it from the system path, which means we would pick up `python3.6` no matter where it was installed.

If you want to add python3.5 to the default properties that's fine - but please remove the absolute paths.

**Comment by CraftSpider** [comment]
Fixed, thank you for the patience

**Comment by apmorton** [comment]
See comments on https://github.com/mattgodbolt/compiler-explorer-image/pull/313

**Pull request closed without merging**
