### PR TITLE
lib/exec.js: verify stream validity

### PR DESCRIPTION
**Pull request by ilAYAli**
* setupOnError
* setupStream

These checks prevent the following error in the output window:
"Internal Compiler Explorer error: TypeError: Cannot read property
'on' of undefined" on macOS

### CODE REVIEW

**Comment by partouf** [comment]
I haven't checked recently, but this has never a problem for me. Is it needed for a specific compiler, or was this error during execution?

**Comment by ilAYAli** [comment]
```
I see this with the default compiler on macOS Mojave:
/tmp/ /usr/bin/clang++ --version
Apple LLVM version 10.0.0 (clang-1000.10.44.2)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

and
```
/tmp/ /Users/petter/local/bin/clang++ --version
clang version 8.0.0 (http://llvm.org/git/clang.git 2bc1c8b8c87e6b0e27d66dcb05955449b2e5a6db) (http://llvm.org/git/llvm.git 794b30e75b840b4115dc956bb23c211f99dcbe26)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Users/petter/local/bin
```

related to: https://github.com/mattgodbolt/compiler-explorer/issues/429

**Comment by partouf** [comment]
can you run CE with node app.js --debug to see what is being executed just before this error?

**Comment by ilAYAli** [comment]
console output:
```
Internal Compiler Explorer error: TypeError: Cannot read property 'on' of undefined
    at setupOnError (/Users/petter/source/mine/compiler-explorer/lib/exec.js:76:16)
    at execute (/Users/petter/source/mine/compiler-explorer/lib/exec.js:97:5)
    at Object.sandbox (/Users/petter/source/mine/compiler-explorer/lib/exec.js:133:16)
    at DefaultCompiler.execBinary (/Users/petter/source/mine/compiler-explorer/lib/base-compiler.js:135:21)
    at DefaultCompiler.postProcess (/Users/petter/source/mine/compiler-explorer/lib/base-compiler.js:586:32)
    at stat.then.catch.then (/Users/petter/source/mine/compiler-explorer/lib/base-compiler.js:234:30)

Compiler returned: -1
```

debug output:
```
info: none
info: Sandbox execution (sandbox disabled) /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler118825-68827-1wqh6wy.t255/output.s
debug:  type=executing, command=/var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler118825-68827-1wqh6wy.t255/output.s, args=[], env=undefined
error: Error during compilation TypeError: Cannot read property 'on' of undefined
    at setupOnError (/Users/petter/source/mine/compiler-explorer/lib/exec.js:76:16)
    at execute (/Users/petter/source/mine/compiler-explorer/lib/exec.js:97:5)
    at Object.sandbox (/Users/petter/source/mine/compiler-explorer/lib/exec.js:133:16)
    at DefaultCompiler.execBinary (/Users/petter/source/mine/compiler-explorer/lib/base-compiler.js:135:21)
    at DefaultCompiler.postProcess (/Users/petter/source/mine/compiler-explorer/lib/base-compiler.js:586:32)
    at stat.then.catch.then (/Users/petter/source/mine/compiler-explorer/lib/base-compiler.js:234:30)
info: ::1 "POST /api/compiler/%2FUsers%2Fpetter%2Flocal%2Fbin%2Fclang%2B%2B/compile" 200
express deprecated req.host: Use req.hostname instead node_modules/raven/lib/client.js:596:19
express deprecated req.host: Use req.hostname instead node_modules/raven/lib/client.js:596:47
Error: spawn /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler118825-68827-1wqh6wy.t255/output.s EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by partouf** [comment]
So it's upon executing your compiled sourcecode while also getting an EACCES.
Can you see what the result from const child = child_process.spawn() actually is here? Is child itself also undefined, and/or does it have any other information? It might be more useful to detect that so that CE gives a more useful error message about the problem.

**Comment by ilAYAli** [comment]
Here is the entire debug output.
[log.zip](https://github.com/mattgodbolt/compiler-explorer/files/2416993/log.zip)

/me is AFK for ~ 8 hours.

**Comment by partouf** [comment]
So I'm super late to actually be testing this, and couldn't reproduce until I looked at the logging again...
And I noticed the program is being compiled with -S, which means it doesn't actually produce a binary to execute. Hence the errors...

You need to click the 11010 button first before trying to execute.

**Comment by partouf** [comment]
merging, because this change can't hurt

**Pull request merged**
