### PR TITLE
rust: Update rust deps to support new mangling scheme

### PR DESCRIPTION
**Pull request by lzutao**
Hope this support demangle new mangling scheme: https://www.reddit.com/r/rust/comments/bvifst/psa_new_rust_symbol_mangling_is_now_in_nightly/

New update log:
```semver
% cargo update
    Updating crates.io index
    Updating aho-corasick v0.6.6 -> v0.7.3
    Updating lazy_static v1.0.2 -> v1.3.0
    Removing libc v0.2.42
    Updating memchr v2.0.1 -> v2.2.0
    Updating regex v0.2.11 -> v1.1.6
    Updating regex-syntax v0.5.6 -> v0.6.6
    Updating rustc-demangle v0.1.8 -> v0.1.15
    Updating thread_local v0.3.5 -> v0.3.6
    Updating ucd-util v0.1.1 -> v0.1.3
    Removing unreachable v1.0.0
    Updating utf8-ranges v1.0.0 -> v1.0.2
    Removing void v1.0.2
```

### CODE REVIEW

**Comment by lzutao** [comment]
@mattgodbolt Could you delete the travis cache and restart the build?
The cached rust version is 1.30.0 and it will not change even if I change
the configuration.

**Comment by lzutao** [comment]
No need then. I found a way to workaround this problem.

**Comment by lzutao** [comment]
Could you review this PR, @partouf ?

**Comment by RabsRincon** [comment]
Hi! Sorry about the delay, this PR has a bit of a timming issue. We are moving all the tools from demangling etc to a separate repo with #1421 We are going to be merging it soon, so I'll be sure to let you know when you can open a PR in the new repo!
Again, sorry for keeping you waiting, and thanks for taking the time to keep our rust support somewhat healthy! :)

**Comment by lzutao** [comment]
Thanks for letting me know. I'll open a new PR in the new repo when
it's ready.

**Comment by mattgodbolt** [comment]
Thanks: and sorry for the confusion! Let me know if I can help in any way! Note to @RabsRincon we don't (yet) have an installation story for the tools...I did the first lot manually.

**Pull request closed without merging**
