### PR TITLE
gccdump: add basic syntax highlighting

### PR DESCRIPTION
**Pull request by dkm**
Based on 'mylang' example that mostly works correctly for gimple.
Added all RTL classes and ';' prefixed comment.

Still a lot could be done, but it's better than without any color
highlighting.

I don't have the IDE installed here, so I'm note sure the coding style is correct. If needed, I can recheck that later.

### CODE REVIEW

**Comment by RabsRincon** [comment]
Checking before merging, I've noticed that the highlighting also works even if the contents of the window is the "File for selected pass is empty." message or similar. Would be great to disable highlighting if a custom message is displayed.
Could that be done?

**Comment by dkm** [comment]
Sure! Did not tried that! Will rebase the changes ! Thanks for the tests ?!! 😃

**Comment by honggyukim** [comment]
@dkm Thanks for doing this : )

**Comment by dkm** [comment]
Ooops, found a bug, don't merge yet !

**Comment by dkm** [comment]
Ok, should be correct now. Gimple highlighting is really basic... As it's not really close to anything else, I guess the best solution would be to create a custom lang. I'm not sure I'll find time for this in the near future :/

**Comment by dkm** [comment]
@honggyukim do not hesitate to give more feedback/ideas :)

**Comment by RabsRincon** [comment]
After testing now I don't have anything else to say than this looks great!
Thanks for the effort you've put on the gcc dumps

**Comment by dkm** [comment]
Thanks for merging it !

**Pull request merged**
