### PR TITLE
always allow custom assembly labels

### PR DESCRIPTION
**Pull request by partouf**
(as they are included in the linux binaries too)

Solves #577

### CODE REVIEW

**Comment by jaredwy** [comment]
Is this the right way to solve this? 
Im thinking it might be better fixed by including it in clang. The user did explicitly ask for it?

**Comment by partouf** [comment]
but it Is in clang, the output is there, for some reason however asm.js decided it was unused. the formatting is slightly different between gcc and clang, but the #app #no_app for custom assembly is the same in both

**Comment by jaredwy** [comment]
this is what I am saying, if the user has asked for it, shouldn't we output it in clang rather than remove it from gcc? 

I guess what I am asking is, isn't clang the broken output here?

**Comment by partouf** [comment]
I didn't remove it, it's actually retained in clang this way
https://github.com/mattgodbolt/compiler-explorer/pull/685/files#diff-848733f56cea17641e864b46a771ad4eR219 makes sure every label between inline-assembly tags is left alone

**Comment by partouf** [comment]
The last change affects the way the label is shown and not treated as anything else but a label inside inline assembly.

This could be a stand alone solution if you still would want .LX0 to filter out the label (because it's unused)

**Comment by partouf** [comment]
I would like some input to clean up this PR:

1. Do we want GCC to output the label correctly as an unused label?

or

2. Do we want inline assembly labels to always show despite the unused filter?

**Comment by partouf** [comment]
I'll delete this PR and remake as to only do 1

**Pull request closed without merging**
