### PR TITLE
Move privacy configuration to a cookie with a configurable domain

### PR DESCRIPTION
**Pull request by mattgodbolt**
See #1109, and the discussion therein. Will need a separate PR to move the cookie consent itself to using cookies (ironically).

### CODE REVIEW

**Comment by RabsRincon** [comment]
Should we add the cookies consent plugin changes to this PR aswell?

**Comment by mattgodbolt** [comment]
Would love to add cookie consent too! Just wasn't sure on how easy that was going to be :)

**Comment by RabsRincon** [comment]
I have not been able to do this yet for this monday session (Got short of time this week!) Feel free to merge this one, and I'll be able to upgrade the cookieconsent repo on thursday

**Comment by mattgodbolt** [comment]
Thanks @RabsRincon - I think I will merge and let you make the cookieconsent changes! :smile_cat:

**Pull request merged**
