### PR TITLE
Adding in LDC opt view support

### PR DESCRIPTION
**Pull request by jaredwy**

### CODE REVIEW

**Comment by JohanEngelen** [comment]
Works for me locally!

**Comment by mattgodbolt** [comment]
I plan on doing a site update in the next day or two once I get an hour or so to test it all.

**Comment by JohanEngelen** [comment]
great

**Comment by mattgodbolt** [comment]
During testing this bug didn't appear to be fixed. @jaredwy is there anything missing from the configuration in the `d.amazon.properties` file do you think?
screenshot from 2017-09-04 07-59-55

**Comment by JohanEngelen** [comment]
@mattgodbolt The live website works. It's not the AST button (rightmost), it's the button to the leftof it (2nd from the right).
Try it with this code:
```
extern(C):

alias T = int;
T byPtr(int n, T *c) {
  T sum;
  for (int i=0; i < n; ++i)
    if (i > 0)
      sum += *c;
  return sum;
}

T byRef(int n, ref T c) {
  T sum;
  for (int i=0; i < n; ++i)
    if (i > 0)
      sum += c;
  return sum;
}
```

**Comment by jaredwy** [comment]
It was just the opt view that this should work with. Seems ok. Does ldc
support the AST output?

**Comment by mattgodbolt** [comment]
Whoops! I can't believe I pressed the wrong button :) It was early in the
morning and I hadn't had enough coffee! haha

**Comment by JohanEngelen** [comment]
> Does ldc support the AST output?

No.

**Pull request merged**
