### PR TITLE
Alternative UI layout for Executor pane

### PR DESCRIPTION
**Pull request by partouf**
Divides up the different parts of execution, and adds toggle buttons to turn those parts on and off.

**Just Stdout active**
image

**Arguments and Stdin**
image

**Everything on**
image

**Hidden labels**
image

### CODE REVIEW

**Comment by RabsRincon** [comment]
I love this 11/10

**Comment by RabsRincon** [comment]
Maybe it its and I just can't see it, but, I think the buttons states should be saved in the plane state, right? So a link can choose what to show.
Also, does stdout need to be togglable? I think just not showing it if there's nothing to show would be better, right? It's on by default too, which is also a good solution.

:)

**Comment by mattgodbolt** [comment]
Oh wow! thanks Partouf! Will have to check this out :)

One thing that would be cool in either is to make the inputs resizable. But I don't know how to do that (this is the main thing I think @steveire needed for his thing too...but I couldn't work out how)

**Comment by mattgodbolt** [comment]
Looks great @partouf - thank you :)

Some thoughts:

* The default doesn't have the compiler pane open. Might be a bit confusing at first as it's not clear what compiler you're getting (though it does say so in the window title). I can see why it might not matter in most cases.
* The `stdout` button confused me: is it supposed to be toggleable? Or is it permanently on?
* I agree with Rubén in that we need to persist the "is it toggled on or not" state.

If we all like this, then I propose we merge this into Rubén's branch, look at the very minor remaining things, and then consider releasing it?

Thoughts? :)

I'm so excited at this collaborative effort: you folks are amazing :)

**Comment by RabsRincon** [comment]
I have merged this into the original branch, along with the fixes you mentioned, plus some minor changes too. :)

**Pull request merged**
