### PR TITLE
fix: package.json to reduce vulnerabilities

### PR DESCRIPTION
**Pull request by sdrees**
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-JS-MORGAN-72579
- https://snyk.io/vuln/npm:clean-css:20180306
- https://snyk.io/vuln/npm:constantinople:20180421
- https://snyk.io/vuln/npm:lodash:20180130
- https://snyk.io/vuln/npm:ssri:20180214

... but, no tests or anything was run, so I am happy if this PR is ignored or implemented otherwise.

### CODE REVIEW

**Comment by partouf** [comment]
It seems that this aws-sdk upgrade behaves differently in that it explicitly asks for credentials and makes yarn test hang on Windows.

I did update Morgan separately to 1.9.1, that caused no issues.

Thanks for the PR in any case, leaving this open so we can look further into upgrading the aws-sdk

**Comment by mattgodbolt** [comment]
@sdrees or @partouf any thoughts on how to fix the "yarn test" issue on windows? I don't have a windows box to test on, which test is causing the aws-sdk to ask for creds? I know we mock out some of the stuff...there must be a way to get around this :)

**Comment by mattgodbolt** [comment]
I'm going to close this: seems we're running with a package-lock.json aws-sdk of
```
    "aws-sdk": {
      "version": "2.448.0",
```

But I'll up the minimum aws-sdk anyway. I think probably an `npm audit fix` along the way

**Comment by mattgodbolt** [comment]
(Thanks @sdrees for bringing this up :-) )

**Pull request closed without merging**
