### PR TITLE
Add HFSM state machine library

### PR DESCRIPTION
**Pull request by andrew-gresyk**

### CODE REVIEW

**Comment by andrew-gresyk** [comment]
Adding compiler-explorer-image PR: https://github.com/mattgodbolt/compiler-explorer-image/pull/70

**Comment by mattgodbolt** [comment]
Will bounce into prod once the CI build has finished.

**Comment by andrew-gresyk** [comment]
Awesome!
Thanks a lot Matt!

**Comment by mattgodbolt** [comment]
I've pushed it to the beta site (https://godbolt.org/beta) - can you check it looks OK there? If so I'll push to the live site.

**Comment by mattgodbolt** [comment]
@andrew-gresyk ^ :) looks good to me, will wait for you to check it out on the beta site as above, else it'll go out anyway the next push :)

**Comment by andrew-gresyk** [comment]
Beta looking good!

**Comment by mattgodbolt** [comment]
Pushing to prod: thanks for checking!

**Comment by mattgodbolt** [comment]
In prod. Thanks for your submission! :grinning: Seems you're in London, and go to the London meetups - give them a "hello" from me next time you meet!

**Comment by andrew-gresyk** [comment]
I will!
We met in Bierschenke pub, when you came to London in December.
Remember Valentin? :)

**Comment by andrew-gresyk** [comment]
https://www.meetup.com/CppLondon/photos/28471802/467507615/#467507615

**Comment by mattgodbolt** [comment]
Ohhhh! You confused me by having a different name!! :grin: nice to hear from you again, I do fondly remember that beer, and in fact I remember you talking about this library now!

**Comment by andrew-gresyk** [comment]
Yeah, great discussions too!

**Pull request merged**
