### PR TITLE
Demangling for MSVC CL when using undname.exe

### PR DESCRIPTION
**Pull request by partouf**
Not too happy about this code, but it does work.

Is WSL-CL in use? Should probably change it for that one as well..

(As to setting undname as the demangler in the properties files, before that happens I should probably find out what .dll's undname needs and which ones should switch to native windows dll's instead of the Wine dll's)

### CODE REVIEW

**Comment by RabsRincon** [comment]
WSL-CL is indeed in use. If you plan on adding it, I can hold the merge until you're done :)

**Comment by partouf** [comment]
Ok, I think it’s using the windows vm environment right? I only have Win10 home so I can’t really test it.

Do we have anyone that can test after I’ve done changes?

**Comment by RabsRincon** [comment]
Maybe if we ask nicely enough, @AndrewPardoe might be able to (Or know someone who does) 😄

**Comment by AndrewPardoe** [comment]
Yes, I'll enlist and give this a shot. Thanks for the heads-up!

**Comment by partouf** [comment]
Refactored in a way that I'm reasonably sure this will not at least fail to run.

So @AndrewPardoe if you check out this branch and add to your properties file:
group.cl.demangler=/your/path/to/undname.exe

I assume you'll get better results from it than executing it via Wine :cry: .

**Comment by AndrewPardoe** [comment]
I'm stuck, unfortunately. Commit 43c16a introduced conditional variables into the makefile. For some reason they aren't working under WSL. I've sent mail internally asking for help.

**Comment by AndrewPardoe** [comment]
OK, got this branch cloned locally, but I think there's more setup work to do. What am I supposed to be seeing? This is what I've got: 

`Microsoft (R) C++ Name Undecorator
Copyright (C) Microsoft Corporation. All rights reserved.

Undecoration of :- "/mnt/c/tmp/compiler-explorer-compiler1171113-1754-15ci5f7.tt1ci/output.s"
is :- "/mnt/c/tmp/compiler-explorer-compiler1171113-1754-15ci5f7.tt1ci/output.s"`

**Comment by partouf** [comment]
So the tmpdir is working, but apparently undname sees the filename as a symbol to translate.

undname is supposed to see it as a filename and then read the file and use that as input

So I'm guessing either it doesn't recognize this as a path, or it doesn't return as an existing file.

I think maybe this could be solved by replacing the path to /mnt/c/ with c:/
Maybe even put the slashes the other way just be sure.

I'll get on it.

**Comment by AndrewPardoe** [comment]
I honestly haven't even looked at your code changes yet--I was first focused on the makefile fix, then just applied your changes blindly. 

I might have a chance to look at this today. If you have any pointers (besides the above) feel free to email or DM me on Slack.

**Comment by partouf** [comment]
The change I just committed is probably the solution.
I'm actually surprised it worked under WINE as it was.

**Comment by AndrewPardoe** [comment]
OK, looks beautiful! Thanks!

**Comment by AndrewPardoe** [comment]
I've now tested with an x86 compiler that has some more fun calling conventions (`__declspec(naked)`, anyone?) and remain happy with the results of my testing.

**Comment by RabsRincon** [comment]
Note that one of the tests is currently failing after @AndrewPardoe's PR got merged. Any idea why?

**Comment by mattgodbolt** [comment]
Failure is:
```
  1) Paths Linux -> Windows path:
     TypeError: Cannot read property 'substring' of undefined
      at Compile.compile.filename (lib/compilers/WSL-CL.js:49:52)
      at Context.<anonymous> (test/win-path-tests.js:66:22)
```

**Comment by AndrewPardoe** [comment]
I think this has to do with my comment above: @partouf has referenced the temp directory as `c:\tmp`, how it used to be hardcoded.  Now the tests should be using the actual temp directory for the machine *or* setting the temp directory with the `tmpDir` option.  

1. Are you running tests on the WSL-CL, or is this from Wine? 
2. How do I run tests? I can take a stab at fixing. I can dig out my Linux machine : )

**Comment by mattgodbolt** [comment]
Hi @AndrewPardoe !

1. Tests are run on Linux directly (https://travis-ci.org/ is the only CI we run on, and that's Linux). If the tests don't work on Linux we'll have to disable these somehow.
2. `npm test` is how we run the tests on Linux (where `npm` picks up all the configuration from the `package.json`)

**Comment by partouf** [comment]
I'm guessing this has something to do with the fact that I set tmpDir in the unit test to make it work, so all that is needed is to set winTmp instead @ https://github.com/mattgodbolt/compiler-explorer/pull/682/files#diff-76b2cc1bba1753a03b186a7bf4eb6f8fR65

**Comment by AndrewPardoe** [comment]
Actually, I think the second half of that test--the one that creates a WSL compiler when running under Wine--is invalid. The test may pass, but I don't think it's actually testing anything useful under Wine.

Can you guard that block with a check for process.env.wsl? Alternatively, you can remove that block, but it might be nice to have a suite of WSL tests one day. 

```
// AP: Detect if we're running under Windows Subsystem for Linux. Temporary modification
// of process.env is allowed: https://nodejs.org/api/process.html#process_process_env
if ((child_process.execSync('uname -a').toString().indexOf('Microsoft') > -1) && (opts.wsl))
    process.env.wsl = true;
```

**Comment by partouf** [comment]
@AndrewPardoe it unit-tests the filename function so that I knew my assumptions for using it were correct for using it in the execution of undname. That's all it tests and it was enough for me.

You're right in implying that it doesn't test the integration of it all, but I've never been the person to test things that might fail if you have something installed or not (wine and wsl are entirely optional and so the integration tests would fail in the cases someone wouldn't have them installed).

So I disagree with only testing filename() if we're actually running in wsl. Some functions like filename() should be unit testable without a special environment.

**Comment by AndrewPardoe** [comment]
I'm just confused what it means to use the WSL codepath on a non-Windows machine.

**Comment by partouf** [comment]
It means that I could test it "enough" so I could be reasonably sure that it would work in a situation where I couldn't actually test it in a WSL environment. That's all, really.

**Comment by partouf** [comment]
Commited fix to unittest

**Comment by AndrewPardoe** [comment]
Ah, thanks for explaining!

**Comment by partouf** [comment]
Finally did some digging and found a way to fix the demangling under Wine, we either need to set vcruntime140.dll or ucrtbase.dll to native. I'm guessing ucrtbase.dll is the finer grained choice.

I found I can set the environment variable WINEDLLOVERRIDES="ucrtbase=native" to fix it without having to fiddle in the GUI configuration tool of Wine.

But now the question, how can we set that up for CE?

**Comment by mattgodbolt** [comment]
@partouf Wow great finds. The wine environment is currently in https://github.com/mattgodbolt/compiler-explorer/blob/master/c-preload/compiler-wrapper#L11 - so we can try putting magic env vars there

**Comment by partouf** [comment]
seems vcruntime14 was the better choice after all, I just made the exec use the default settings to use the compile-wrapper specifically for undname

**Pull request merged**
