### PR TITLE
Implemented notification popup if compiler options includes any that might be "unwise"

### PR DESCRIPTION
**Pull request by LukaPrebil**
This implements request from [issue 1379](https://github.com/mattgodbolt/compiler-explorer/issues/1379#issue-444078354), while adding ability to add more unsafe options

### CODE REVIEW

**Comment by partouf** [comment]
Later on we also have to change this to a per-compiler configurable setting, -march is just Clang and other compilers and languages will have other options.

**Comment by partouf** [comment]
@LukaPrebil I talked to @RabsRincon about this, and perhaps the best you can do is to put this as the second parameter at the call to this.alertSystem.notify
```{group: 'unwiseOption', collapseSimilar: true}```

After that I think we can merge this.

**Comment by LukaPrebil** [comment]
@partouf I've added the grouping, as suggested. If you wish, i can also implement it in a way that checks if options actually changed :)

**Comment by apmorton** [comment]
Both `"-march=native"` and `-march="native"` in the options box work, but won't trigger the warning - it's definitely a bit pedantic of an issue, just thought I would mention it.

I also wonder if it may be preferable to implement the checks server side and have the client simply pop any notifications that appear in the API response.

It looks like the server side already has logic to deal with quoting in compiler arguments, since the quotes in my examples above disappear from the full list of compiler flags that appear when you hover over the green checkmark next to the options box.

Might make it easier to implement compiler specific checks in the future. (ICC's equivalent flag is `-qHost` for example).

**Comment by LukaPrebil** [comment]
@apmorton I'm not sure server side is appropriate to check for something that is merely a notification to the user, and has no effect whatsoever on the application itself. Though reusing an existing parser for the options would be nice. I will take a look at what can be done.

**Comment by partouf** [comment]
Am not a fan of putting the logic serverside even though it makes more sense in terms of parsing. We might be able to tweak the clientside argument parsing...

**Comment by mattgodbolt** [comment]
Hey Luka: Apologies for being slow: we're trying to get the scary big "execution support" pushed to prod. Once that's done we will look to merge and release this! Thanks for your patience! (also not quite sure where we are with this and will have to read all this back to work out what the next steps are :))

**Comment by RabsRincon** [comment]
We are going to merge this and work on making it a configurable setting for more compilers. Apologies again for taking so long. :)

**Comment by LukaPrebil** [comment]
Thank you everyone for your comments and suggestions. I will work on a more powerful/general implementation of this feature next :)

**Pull request merged**
